### DISCUSSION TITLE
[BUG] IPV6直连问题

### DISCUSSION THREAD

**Discussion by HomeQi** [nikkinikki-org/OpenWrt-nikki#239] [Q&A]
### 自查

- [X] OpenWrt 22.03 及以上版本的系统
- [X] 使用firewall4（nftables）而非firewall3（iptables）
- [X] 已经安装了 procd-ujail 依赖
- [X] 针对ImmortalWrt，已经关闭了DNSMASQ的`DNS 重定向`选项
- [X] 已停止运行其他代理插件，并确认环境正常

### 确认

- [X] 我已经搜索过Issue，没有找到我的问题
- [X] 我已经查看过Wiki，没有找到解决办法
- [X] 我使用的是由本仓库代码构建的插件，而不是其他Fork
- [X] 我使用的是最新版的插件
- [X] 这确实是插件的问题，而不是核心/面板/订阅转换服务的问题
- [X] 我提供了正确的、有效的、可以帮助DEBUG的信息，而不是随意填写
- [X] 我提供的信息里不包含公网IP、MAC、代理节点等敏感信息

### 系统

ImmortalWrt

### 系统版本

ImmortalWrt 23.05.4 r28061-399f9a1db3 / LuCI openwrt-23.05 branch git-24.265.44782-0ff45d8

### 插件版本

alpha-08dcef8

### 硬件架构

x86_64

### BUG 描述

设置情况：
1. 代理设置-透明代理（IPV6 DNS劫持开启、IPV6代理关闭）
2. 混入配置-全局配置（IPV6 开关开启）
3. 混入配置-DNS配置（IPV6 开关开启）
因为我的魔法没有ipv6，所以没有开启v6的代理，访问iOS客户端的chatgpt，cloudflare会直接连接ipv6地址，导致无法正常使用，同样的情况也出现在docker的安装上。

### 预期行为

国内v4v6双栈，国外仅v4

### 复现步骤

按配置设置后，使用iOS客户端的chatgpt或访问https://registry.hub.docker.com/  （首访v6异常，虽然刷新可以进入，但是会导致群晖下载错误的问题）

### 插件配置

mihomo.status=status
mihomo.config=config
mihomo.config.enabled='1'
mihomo.config.scheduled_restart='0'
mihomo.config.cron_expression='0 3 * * *'
mihomo.config.profile='file:mihomo.yaml'
mihomo.config.mixin='1'
mihomo.config.test_profile='1'
mihomo.config.fast_reload='1'
mihomo.config.upload_profile='/etc/mihomo/profiles/mihomo.yaml'
mihomo.proxy=proxy
mihomo.proxy.transparent_proxy='1'
mihomo.proxy.tcp_transparent_proxy_mode='tproxy'
mihomo.proxy.udp_transparent_proxy_mode='tun'
mihomo.proxy.ipv4_dns_hijack='1'
mihomo.proxy.ipv6_dns_hijack='1'
mihomo.proxy.ipv4_proxy='1'
mihomo.proxy.ipv6_proxy='0'
mihomo.proxy.router_proxy='1'
mihomo.proxy.lan_proxy='1'
mihomo.proxy.access_control_mode='all'
mihomo.proxy.bypass_china_mainland_ip='1'
mihomo.proxy.acl_tcp_dport='21 22 80 110 143 194 443 465 993 995 8080 8443'
mihomo.proxy.acl_udp_dport='123 443 8443'
mihomo.proxy.acl_ip='192.168.66.2'
mihomo.subscription=subscription
mihomo.subscription.name='default'
mihomo.subscription.url='http://example.com/default.yaml'
mihomo.subscription.user_agent='clash'
mihomo.mixin=mixin
mihomo.mixin.log_level='info'
mihomo.mixin.mode='rule'
mihomo.mixin.match_process='off'
mihomo.mixin.ipv6='1'
mihomo.mixin.tcp_keep_alive_idle='600'
mihomo.mixin.tcp_keep_alive_interval='15'
mihomo.mixin.ui_name='metacubexd'
mihomo.mixin.ui_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip'
mihomo.mixin.api_port='9090'
mihomo.mixin.selection_cache='1'
mihomo.mixin.allow_lan='1'
mihomo.mixin.http_port='8080'
mihomo.mixin.socks_port='1080'
mihomo.mixin.mixed_port='7890'
mihomo.mixin.redir_port='7891'
mihomo.mixin.tproxy_port='7892'
mihomo.mixin.authentication='1'
mihomo.mixin.tun_stack='mixed'
mihomo.mixin.tun_mtu='9000'
mihomo.mixin.tun_gso='1'
mihomo.mixin.tun_gso_max_size='65536'
mihomo.mixin.tun_endpoint_independent_nat='0'
mihomo.mixin.dns_port='1053'
mihomo.mixin.dns_mode='redir-host'
mihomo.mixin.fake_ip_range='198.18.0.1/16'
mihomo.mixin.fake_ip_filter='0'
mihomo.mixin.fake_ip_filters='+.lan' '+.local'
mihomo.mixin.fake_ip_cache='1'
mihomo.mixin.dns_respect_rules='1'
mihomo.mixin.dns_doh_prefer_http3='0'
mihomo.mixin.dns_ipv6='0'
mihomo.mixin.dns_system_hosts='0'
mihomo.mixin.dns_hosts='1'
mihomo.mixin.hosts='1'
mihomo.mixin.dns_nameserver='1'
mihomo.mixin.dns_nameserver_policy='1'
mihomo.mixin.geoip_format='mmdb'
mihomo.mixin.geodata_loader='standard'
mihomo.mixin.geosite_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
mihomo.mixin.geoip_mmdb_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb'
mihomo.mixin.geoip_dat_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat'
mihomo.mixin.geoip_asn_url='https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb'
mihomo.mixin.geox_auto_update='1'
mihomo.mixin.geox_update_interval='48'
mihomo.mixin.api_secret='712996'
mihomo.@authentication[0]=authentication
mihomo.@authentication[0].enabled='1'
mihomo.@authentication[0].username='mihomo'
mihomo.@authentication[0].password='712996'
mihomo.@host[0]=host
mihomo.@host[0].enabled='1'
mihomo.@nameserver[0]=nameserver
mihomo.@nameserver[0].enabled='1'
mihomo.@nameserver[0].type='default-nameserver'
mihomo.@nameserver[0].nameserver='223.5.5.5' '119.29.29.29'
mihomo.@nameserver[1]=nameserver
mihomo.@nameserver[1].enabled='1'
mihomo.@nameserver[1].type='proxy-server-nameserver'
mihomo.@nameserver[1].nameserver='223.5.5.5' '119.29.29.29'
mihomo.@nameserver[2]=nameserver
mihomo.@nameserver[2].enabled='1'
mihomo.@nameserver[2].type='nameserver'
mihomo.@nameserver[2].nameserver='223.5.5.5' '119.29.29.29'
mihomo.@nameserver[3]=nameserver
mihomo.@nameserver[3].enabled='1'
mihomo.@nameserver_policy[0]=nameserver_policy
mihomo.@nameserver_policy[0].enabled='1'
mihomo.@nameserver_policy[0].matcher='"rule-set:private_domain,cn_domain"'
mihomo.@nameserver_policy[0].nameserver='223.5.5.5' '119.29.29.29'
mihomo.@nameserver_policy[1]=nameserver_policy
mihomo.@nameserver_policy[1].enabled='1'
mihomo.@nameserver_policy[1].matcher='"rule-set:geolocation-!cn"'
mihomo.@nameserver_policy[1].nameserver='https://dns.cloudflare.com/dns-query' 'https://dns.google/dns-query'
mihomo.editor=editor
mihomo.log=log

### 配置文件
```yaml
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - '+.v2ex.com'
  skip-domain:
    - 'rule-set:cn_domain,private_domain'
    - 'Mijia Cloud'
    - '+.push.apple.com'
    - '+.wechat.com'
    - '+.qpic.cn'
    - '+.qq.com'
    - '+.wechatapp.com'
    - '+.vivox.com'
    - '+.oray.com'
    - '+.sunlogin.net'
rules:
  - DOMAIN,gst.prod.dl.playstation.net,直连
  - DOMAIN-SUFFIX,steamcontent.com,直连
  - DOMAIN-SUFFIX,bittorrent.com,直连
  - DOMAIN-SUFFIX,bttrack.com,直连
  - DOMAIN-SUFFIX,tracker,直连
  - SRC-PORT,34560-34570,直连
  - SRC-PORT,6881-6889,直连
  - SRC-PORT,6969,直连
  - SRC-PORT,8080,直连
  - SRC-PORT,8999,直连
  - SRC-PORT,51413,直连
  - DOMAIN-SUFFIX,cloudflare.com,直连
  - DOMAIN-SUFFIX,posthog.com,REJECT-DROP
  - IP-CIDR,114.247.154.1/24,REJECT-DROP,no-resolve
  - IP-CIDR,106.120.178.6/24,REJECT-DROP,no-resolve
  - DOMAIN-KEYWORD,launchdarkly,REJECT-DROP
  - DOMAIN-KEYWORD,segment,REJECT-DROP
  - DOMAIN-SUFFIX,posthog.com,REJECT-DROP
  - OR,((DOMAIN,lcs-cops.adobe.io), (DOMAIN,photo.adobe.io)),DIRECT
  - DOMAIN-SUFFIX,adobe.io,REJECT
  - RULE-SET,category-public-tracker,REJECT-DROP
  - RULE-SET,private_ip,国内网站,no-resolve
  - RULE-SET,private-direct,国内网站
  - RULE-SET,openai,ChatGPT
  - RULE-SET,private-tracker,国内网站
  - RULE-SET,category-ai-chat-!cn,AI 平台
  - RULE-SET,telegram,Telegram
  - RULE-SET,twitter,Twitter
  - RULE-SET,youtube,YouTube
  - RULE-SET,spotify,Spotify
  - RULE-SET,netflix,NetFlix
  - RULE-SET,disney,Disney
  - RULE-SET,hbo,国际媒体
  - RULE-SET,tiktok,TikTok
  - RULE-SET,github,Github
  - RULE-SET,onedrive,微软服务
  - RULE-SET,microsoft@cn,国内网站
  - RULE-SET,microsoft,微软服务
  - RULE-SET,instagram,脸书服务
  - RULE-SET,facebook,脸书服务
  - RULE-SET,meta,脸书服务
  - RULE-SET,google,谷歌服务
  - RULE-SET,apple-cn,国内网站
  - RULE-SET,apple,苹果服务
  - RULE-SET,paypal@cn,国内网站
  - RULE-SET,paypal,货币平台
  - RULE-SET,category-cryptocurrency,货币平台
  - RULE-SET,cloudflare-cn,国内网站
  - RULE-SET,category-games,游戏平台
  - RULE-SET,category-media-cn,国内网站
  - RULE-SET,category-media,国际新闻
  - RULE-SET,category-social-media-!cn,社交平台
  - RULE-SET,cn_domain,国内网站
  - RULE-SET,geolocation-!cn,国外网站
  - RULE-SET,facebook_ip,脸书服务,no-resolve
  - RULE-SET,google_ip,谷歌服务,no-resolve
  - RULE-SET,netflix_ip,NetFlix,no-resolve
  - RULE-SET,twitter_ip,Twitter,no-resolve
  - RULE-SET,telegram_ip,Telegram,no-resolve
  - RULE-SET,cn_ip,国内网站,no-resolve
  - MATCH,漏网之鱼
log-level: info
mode: rule
find-process-mode: off
keep-alive-idle: 600
keep-alive-interval: 15
ipv6: true
external-ui: ui
external-ui-name: metacubexd
external-ui-url: https://mirror.ghproxy.com/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
external-controller: 0.0.0.0:9090
secret: 712996
allow-lan: true
port: 8080
socks-port: 1080
mixed-port: 7890
redir-port: 7891
tproxy-port: 7892
tun:
  enable: true
  stack: mixed
  device: mihomo
  mtu: 9000
  gso: true
  gso-max-size: 65536
  endpoint-independent-nat: false
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
  dns-hijack: []
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  respect-rules: true
  prefer-h3: false
  ipv6: false
  use-system-hosts: false
  use-hosts: true
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver-policy:
    "rule-set:private_domain,cn_domain":
      - 223.5.5.5
      - 119.29.29.29
    "rule-set:geolocation-!cn":
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query
```

### 插件日志

[2024-10-15 04:15:29] App is enabled.
[2024-10-15 04:15:29] Starting...
[2024-10-15 04:15:29] Use Profile: mihomo.yaml
[2024-10-15 04:15:29] Mixin is enabled, mixin all config.
[2024-10-15 04:15:30] Profile testing...
[2024-10-15 04:15:30] Profile test passed!
[2024-10-15 04:15:30] Start Core
[2024-10-15 04:15:30] Transparent Proxy is enabled.
[2024-10-15 04:15:30] Transparent Proxy: Start.
[2024-10-15 04:15:30] Transparent Proxy: IPv4 DNS Hijack is enabled, IPv4 dns request will redirect to the core.
[2024-10-15 04:15:30] Transparent Proxy: IPv6 DNS Hijack is enabled, IPv6 dns request will redirect to the core.
[2024-10-15 04:15:30] Transparent Proxy: IPv4 Proxy is enabled, set proxy for IPv4 traffic.
[2024-10-15 04:15:30] Transparent Proxy: Bypass china mainland ip is enabled.
[2024-10-15 04:15:30] Transparent Proxy: Destination TCP Port to Proxy: 21 22 80 110 143 194 443 465 993 995 8080 8443.
[2024-10-15 04:15:30] Transparent Proxy: Destination UDP Port to Proxy: 123 443 8443.
[2024-10-15 04:15:31] Transparent Proxy: Router Proxy is enabled, set proxy for router.
[2024-10-15 04:15:31] Transparent Proxy: Lan Proxy is enabled, set proxy for lan.
[2024-10-15 04:15:31] Transparent Proxy: Access Control is using all mode, set proxy for all client.
[2024-10-15 04:15:31] Start Successful!

### 核心日志

time="2024-10-15T04:15:30.366761912+08:00" level=info msg="Start initial configuration in progress"
time="2024-10-15T04:15:30.372030632+08:00" level=info msg="Geodata Loader mode: standard"
time="2024-10-15T04:15:30.372056161+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-10-15T04:15:30.372873657+08:00" level=info msg="Initial configuration complete, total time: 6ms"
configuration file /etc/mihomo/run/config.yaml test is successful

### 附加信息

配置文件适当精简了一点，使用的是真实IP模式，非fakeip模式，目前关闭dns的ipv6，国内外都没有使用v6。
网络拓扑如 https://blog.gazer.win/essay/ikuai-multiwan-bypass-flow-with-openwrt.html 参考（可能稍微有一点复杂，但是就使用来说类似于融合的主路由模式）如果有任何需要补充的信息，我会立即补充上，非常感谢！

**Comment by morytyann** [comment]
打开IPv6代理

**Comment by HomeQi** [comment]
> 打开IPv6代理

已经打开IPV6代理，相关如图
<img width="195" alt="image" src="https://github.com/user-attachments/assets/99d9fde6-85c2-4ba8-863f-d38fa9070717">

ipv6dns劫持、代理、dns的ipv6开启，但是访问依旧出错，显示连接被重置，（ipv6dns劫持和代理开启，关闭dns模块的ipv6后恢复正常）

**Comment by HomeQi** [comment]
> 确认 IPv6 相关的配置是否正确。尽管 DNS 劫持已开启，但如果没有 IPv6 代理，可能会导致连接问题。建议尝试关闭 IPv6 DNS 劫持，看看是否能解决问题。 另外使用[servbay](https://servbay.com)检查开发环境，docker其实跟mac很多不兼容的地方

设置后问题依旧没有解决，但是感谢您的建议！

**Comment by xianren78** [comment]
旁路由吗？

**Comment by HomeQi** [comment]
> 旁路由吗？

网络拓扑如 https://blog.gazer.win/essay/ikuai-multiwan-bypass-flow-with-openwrt.html 不属于旁路模式，dns解析是交由OpenWrt来处理的。

**Comment by morytyann** [comment]
针对对域名发起的连接，解析到IPv6地址≠核心会发起IPv6连接，如果是走代理的话，都是发送域名给节点，然后远端解析；
但是你是Redir-Host模式，客户端收到IPv6的解析结果有可能会发起IPv6连接（看优先级），所以你需要开启IPv6代理，才能保证代理正常工作。

综上，原理上是没问题的，在我的主路由下测试也是正常的，你或许应该排查IPv6的流量是怎么走的，有没有进入到核心。

**Reply by HomeQi** [reply]
目前分析应该是ipv6走了ikuai的adsl1直接出去了，要想办法把网关转到OpenWrt上。能提供一些建议吗？非常感谢！

**Reply by morytyann** [reply]
那我就不知道了，没有用过爱快呢

**Reply by HomeQi** [reply]
好吧，感谢。

**Comment by 1345695** [comment]
想起来一个问题，cloudflare都给所有cdn都开启了ech,所以原因可能是走type65的HTTPS记录导致sni被隐藏统一显示为cloudflare-ech.com，最终分流出问题了

**Reply by 1345695** [reply]
测试发现的确是这样的,https记录会给出正确的v6v4地址，用ipv6会直连重置链接
![image](https://github.com/user-attachments/assets/e098305d-e36f-485e-937c-e2d301e49305)

**Reply by HomeQi** [reply]
这个有什么比较好的办法吗？十分感谢

**Reply by Zerorigin** [reply]
> 这个有什么比较好的办法吗？十分感谢

1、可尝试在 DNS 转发服务器上过滤掉 HTTPS 记录

2、或者在爱快上面用 ACL 规则放行对境内的 IPv6 访问
同时用 ACL 规则掐掉对海外 IPv6 的 80/tcp、443/tcp、443/udp 访问

两种方法任选其一，应该都行

**Reply by 1345695** [reply]
> 这个有什么比较好的办法吗？十分感谢

我都是用smartdns在外面套一层，开两组dns做doh加缓存的屏蔽type65

**Reply by HomeQi** [reply]
> > 这个有什么比较好的办法吗？十分感谢
> 
> 我都是用smartdns在外面套一层，开两组dns做doh加缓存的屏蔽type65

我尝试过mosdns，会有问题，mtp所有的流量都是来自192的，走了直连，可能是我没有设置对，先看看ACL规则是否能解决，如果不行还需要想你请教一下设置的方法，再次表示感谢！

**Reply by HomeQi** [reply]
> > 这个有什么比较好的办法吗？十分感谢
> 
> 1、可尝试在 DNS 转发服务器上过滤掉 HTTPS 记录
> 
> 2、或者在爱快上面用 ACL 规则放行对境内的 IPv6 访问 同时用 ACL 归贼掐掉对海外 IPv6 的 80/tcp、443/tcp、443/udp 访问
> 
> 两种方法任选其一，应该都行

好，我去尝试一下，仅允许国内的访问V6，感谢！

**Reply by 1345695** [reply]
> > > 这个有什么比较好的办法吗？十分感谢
> > 
> > 
> > 我都是用smartdns在外面套一层，开两组dns做doh加缓存的屏蔽type65
> 
> 我尝试过mosdns，会有问题，mtp所有的流量都是来自192的，走了直连，可能是我没有设置对，先看看ACL规则是否能解决，如果不行还需要想你请教一下设置的方法，再次表示感谢！

mosdns一样的，mihomo的请求发到mosdns上做doh再屏蔽一下，应该要把dns劫持关掉用自己设置的解析流程

**Reply by HomeQi** [reply]
> > > > 这个有什么比较好的办法吗？十分感谢
> > > 
> > > 
> > > 我都是用smartdns在外面套一层，开两组dns做doh加缓存的屏蔽type65
> > 
> > 
> > 我尝试过mosdns，会有问题，mtp所有的流量都是来自192的，走了直连，可能是我没有设置对，先看看ACL规则是否能解决，如果不行还需要想你请教一下设置的方法，再次表示感谢！
> 
> mosdns一样的，mihomo的请求发到mosdns上做doh再屏蔽一下，应该要把dns劫持关掉用自己设置的解析流程

可以麻烦给个大致的流程吗？或者方便的话您加我一下（1248302938q），具体的设置能做下参考，谢谢！

**Reply by 1345695** [reply]
> > > > > 这个有什么比较好的办法吗？十分感谢
> > > > 
> > > > 
> > > > 我都是用smartdns在外面套一层，开两组dns做doh加缓存的屏蔽type65
> > > 
> > > 
> > > 我尝试过mosdns，会有问题，mtp所有的流量都是来自192的，走了直连，可能是我没有设置对，先看看ACL规则是否能解决，如果不行还需要想你请教一下设置的方法，再次表示感谢！
> > 
> > 
> > mosdns一样的，mihomo的请求发到mosdns上做doh再屏蔽一下，应该要把dns劫持关掉用自己设置的解析流程
> 
> 可以麻烦给个大致的流程吗？或者方便的话您加我一下（1248302938q），具体的设置能做下参考，谢谢！

mihomo的dns改成127.0.0.1:5336 5337这两个就行了
```
log:
  level: error
  file: "/tmp/mosdns.log"

# API 入口设置
api:
  http: "0.0.0.0:9091"

include: []

plugins:

  # 缓存
  - tag: lazy_cache0
    type: cache
    args:
      size: 4294967295
      lazy_cache_ttl: 0
      dump_file: "/etc/mosdns/cache0.dump"
      dump_interval: 3600

  - tag: lazy_cache1
    type: cache
    args:
      size: 4294967295
      lazy_cache_ttl: 0
      dump_file: "/etc/mosdns/cache1.dump"
      dump_interval: 3600


  # 国内dns
  - tag: forward_local
    type: forward
    args:
      concurrent: 4
      upstreams:
        - addr: "https://223.5.5.5/dns-query"
          idle_timeout: 4294967295
          enable_pipeline: true
  # 国外dns
  - tag: forward_remote
    type: forward
    args:
      concurrent: 4
      upstreams:
        - addr: "https://8.8.8.8/dns-query"
          idle_timeout: 4294967295
          enable_pipeline: true

 
  # 有响应则修改 TTL 并终止返回
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: has_resp
        exec: accept



  # 拒绝type65
  - tag: query_is_reject_domain
    type: sequence
    args:
      - matches: qtype 65
        exec: reject 3


  # 主要的运行逻辑插件
  # sequence 插件中调用的插件 tag 必须在 sequence 前定义，
  # 否则 sequence 找不到对应插件。
  
  
  #国内解析流程
  - tag: lc_sequence
    type: sequence
    args:
      - exec: $lazy_cache0
      - exec: $query_is_reject_domain
      - exec: $forward_local
      - exec: jump has_resp_sequence
  #国外解析流程
  - tag: re_sequence
    type: sequence
    args:
      - exec: $lazy_cache1
      - exec: $query_is_reject_domain
      - exec: $forward_remote
      - exec: jump has_resp_sequence

  # 启动 udp 服务器。
#国内127.0.0.1:5336
  - tag: udp_server5336
    type: udp_server
    args:
      entry: lc_sequence
      listen: "127.0.0.1:5336"
#国外127.0.0.1:5337
  - tag: udp_server5337
    type: udp_server
    args:
      entry: re_sequence
      listen: "127.0.0.1:5337"

```
