### DISCUSSION TITLE
DNS详细设置与规则用来解决谷歌商店问题（绕过中国大陆模式下）

### DISCUSSION THREAD

**Discussion by darknesswei** [nikkinikki-org/OpenWrt-nikki#278] [General]
在不开启绕过中国大陆模式下，谷歌商店无法下载。
推测是规则和fakeip的问题。
# GEO设置：
```
geox-url:
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  asn: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb"
```
实际使用google的规则可能太过于混乱，googlefcm，cnip，proxyip，看连接还有youtube的规则影响，你会发现你根本不知道用哪个。
我只使用了四条规则测试，在绕过中国大陆模式下，geoip兜底走的直连，其余的全部代理，能正常下载，并且基本不耗费机场的流量。
```
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,全球直连 
  - DOMAIN-SUFFIX,clientservices.googleapis.com,节点
  - DOMAIN-SUFFIX,services.googleapis.cn,节点
  - MATCH,其他
```
xn--ngstr-lra8j.com在绕过中国大陆模式下，基本可以说是秒下，开节点也能用，速度慢一些。
# dns设置，fakeip一定要特别注意。
dns劫持开启，不使用其他的套娃。
```
# DNS模块
dns:
  enable: true
  ipv6: true  #不用的话使用false
  default-nameserver: #解析dns,DNS上游
    - 223.5.5.5

  nameserver: #默认域名dns
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

  proxy-server-nameserver: #解析代理节点的域名
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
```
proxy-server-nameserver说实话官方文档没弄明白，不知道究竟是只解析vps的ip域名还是解析走节点的域名dns，反正都走代理了，直接上国外的完事，加密不加密都行，不加密延迟低一点。
```
  direct-nameserver: #直连出口DNS
    - system  #默认路由器dns，可以自己选运营商或者公共dns

  nameserver-policy: #指定域名DNS，优先级高于nameserver/fallback
    "geosite:private":
    - 223.5.5.5  #可以换运营商dns
    - 119.29.29.29  #可以换运营商dns
    "geosite:geolocation-!cn":
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist #命中规则返回真实ip
  fake-ip-filter:
    - '*.lan'
    - "+.local"
    - 'geosite:private'
    - 'geosite:cn'
    - 'geosite:geolocation-!cn'  #绕过大陆模式下，不给谷歌返回真实的vpsip会导致谷歌商店无法使用
 
```
#关于防泄露
感觉意义不大，例如chinamax规则集直接都把

> https://browserleaks.com/webrtc

写成了本地ip直连，你再怎么查都显示你的本地ip，要么规则覆盖，要么不用这个规则集。
基本上分流做好，dns很难漏，没有用fallback是因为官网说了只做备用。
