### DISCUSSION TITLE
求教一下各位大佬，error dial tcp i/o timeout dial tcp  i/o timeout相关日志是什么意思

### DISCUSSION THREAD

**Discussion by refined-fish** [nikkinikki-org/OpenWrt-nikki#345] [Q&A] [answered]
如图，IO超时？是提示有哪里有问题吗，运行起来就一直有这样的日志
![image](https://github.com/user-attachments/assets/83b15191-5ff3-48ac-974d-8385ed1bf6d2)

**Comment by morytyann** [comment, marked as answer]
字面意思，连不上，很正常的，不必在意。

**Reply by refined-fish** [reply]
hhh好的，就是看见一堆连不上，还以为可能哪里配置有问题，但是实际体验好像又没受到影响

**Reply by refined-fish** [reply]
具体有啥原因吗，旧链接被清除所以连不上？

**Reply by morytyann** [reply]
可能是这部分微软服务被墙了，或者是本来就连不上但是对业务不影响所以微软也没处理。

**Reply by refined-fish** [reply]
这么说我才注意到，报错的都是直连，是我智障了🤣

**Reply by morytyann** [reply]
不知道你有没有用WPS，如果你装了WPS你会发现它经常发起对IP:6881的连接，也会刷很多的timeout日志，只要不影响你上网/使用程序/APP，忽略就可以。

**Reply by morytyann** [reply]
![image](https://github.com/user-attachments/assets/f80a9d0a-f47b-4066-87a1-a8aa74a7c5f6)

**Reply by refined-fish** [reply]
我上级有geoip@cn的分流，流量不会进入openWRT，而且也开了绕过大陆，应该也不会进去，所以还没注意到过hh

**Reply by morytyann** [reply]
没事，截个图给你看看，能看到refused和timeout一直在刷，但是WPS依旧好用。

**Reply by refined-fish** [reply]
> 没事，截个图给你看看，能看到refused和timeout一直在刷，但是WPS依旧好用。

🤣太抽象了，这搞的是什么飞机，如果没开绕过我估计也会嫌他浪费性能然后去把绕过开了，或者直接在上级（爱快）把域名ban了

**Reply by refined-fish** [reply]
大佬，还想顺带请教一个问题，mihomo文档指出DNS解析顺序为先匹配规则，若命中域名代理，则会远程解析
我的规则包含
![image](https://github.com/user-attachments/assets/25d83468-65d5-4511-bb89-d88f8873b58a)
理论上 `raw.githubusercontent.com` 应该发送给自动选择的代理节点解析，但是为什么还能在日志看到对应的解析记录呢（更难绷的是这几个DNS好像还被掐了解析失败）
![image](https://github.com/user-attachments/assets/5e87fb33-a63c-4f63-be09-33ad76a81568)
以下是我的DNS配置
```
public-dns: &public-dns
  - dhcp://wan   # 指定网卡获取的DNS，硬路由的wan口网卡名为wan
  - dhcp://eth1  # 指定网卡获取的DNS，软路由的wan口网卡名为最后一张网卡，双口就是eth1
  - 223.5.5.5    # 阿里主DNS
  - 223.6.6.6    # 阿里副DNS

secure-dns: &secure-dns
  - https://8.8.8.8/dns-query   # 谷歌主DNS
  - https://1.1.1.1/dns-query   # Cloudflare主DNS
  - https://1.0.0.1/dns-query   # Cloudflare次DNS

dns:
  enable: true  #⭕启用dns
  prefer-h3: true  # 优先使用HTTP/3，DoH能加速
  listen: 0.0.0.0:1053  #⭕DNS监听端口，仅支持udp
  ipv6: true  # 是否解析ipv6地址，否则返回空结果
  enhanced-mode: redir-host  #⭕DNS处理模式：redir-host/fake-ip，fake-ip更快但引入问题（缓存fakeip后无法故障切换）
  fake-ip-range: 198.18.0.1/16  # fakeip 下的 IP 段设置，tun接口的默认 IPV4 地址 也使用此值作为参考
  fake-ip-filter:  # fakeip过滤
    - geosite:category-ads-all,category-games,cn,private
  fake-ip-filter-mode: blacklist  # 黑/白名单模式，白名单下 filter 会返回 fake-ip
  use-hosts: true  # 查询配置文件 hosts
  use-system-hosts: true  # 查询系统 hosts
  respect-rules: false  # DNS请求遵循路由规则，需先配置好 proxy-server-nameserver，否则出现鸡蛋问题
  
  nameserver-policy:  # 优先级高于nameserver
    'geosite:category-ads-all': rcode://success  # 匹配广告域名
    'geosite:cn,apple,private': *public-dns  # 匹配中国，苹果域名，私有地址
    'geosite:geolocation-!cn': *secure-dns   # 匹配非中国域名
  proxy-server-nameserver: *secure-dns  # 解析节点域名的DNS，不指定则遵循namepolicy
  nameserver: *public-dns  # 默认DNS组，域名未命中 nameserver-policy 时使用
  direct-nameserver: *public-dns  # direct策略组的 DNS 服务器，不填则遵循nameserver-policy
```
