### DISCUSSION TITLE
Welcome to OpenWrt-nikki Discussions!

### DISCUSSION THREAD

**Discussion by morytyann** [nikkinikki-org/OpenWrt-nikki#46] [Announcements]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by ForestL18** [comment]
Hope to add the TUN mode later, thanks.

**Reply by morytyann** [reply]
Maybe in August

**Reply by morytyann** [reply]
I add tun proxy mode in [tun branch](https://github.com/morytyann/OpenWrt-mihomo/tree/tun), you can try it by build it yourself or just use packages build by [GitHub Action](https://github.com/morytyann/OpenWrt-mihomo/actions/workflows/build.yml)

**Comment by mswarmtree** [comment]
请问怎么自己手动更新metacubexd面板？在面板里点更新后直接崩

**Reply by morytyann** [reply]
插件还不支持，如果想更新的话，禁用MetaCubeXD再启用MetaCubeXD，或者移除/etc/mihomo/run/ui/metacubexd文件夹后重启服务
面板里点击更新的话，会直接覆盖整个ui文件夹，核心不支持配置多个面板

**Comment by t20240919** [comment]
👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏👏🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
太棒了,简洁.

请教一下啊,局域网dns服务器的数据经过op时会被劫持吗?它两如何共存,比如,我只需要Mihomo负责代理,dns交给局域网的另一台ADGUARD服务器(比较幸运可直连国外加密地址).

**Reply by morytyann** [reply]
应该有两种办法

1. 打开 DNS 劫持，将Mihomo的DNS上游指向ADG，即客户端 -> Mihomo -> ADG
2. 关闭 DNS 劫持，将DNSMasq上游指向ADG，ADG上游指向Mihomo，即客户端 - > DNSMasq -> ADG -> Mihomo（ADG和Mihomo的顺序可以交换

但是我没测试过，理论可行

**Reply by 625045508** [reply]
> 应该有两种办法
> 
> 1. 打开 DNS 劫持，将Mihomo的DNS上游指向ADG，即客户端 -> Mihomo -> ADG
> 2. 关闭 DNS 劫持，将DNSMasq上游指向ADG，ADG上游指向Mihomo，即客户端 - > DNSMasq -> ADG -> Mihomo（ADG和Mihomo的顺序可以交换
> 
> 但是我没测试过，理论可行

DNSmasq 端口改为0    Adguardhome 端口设置53    adg 上游指向 nikki ， 发现 adg不显示客户端ip 和请求的dns，是哪没设置对嘛？

**Reply by xkdvSrPD** [reply]
> > 应该有两种办法
> > 
> > 1. 打开 DNS 劫持，将Mihomo的DNS上游指向ADG，即客户端 -> Mihomo -> ADG
> > 2. 关闭 DNS 劫持，将DNSMasq上游指向ADG，ADG上游指向Mihomo，即客户端 - > DNSMasq -> ADG -> Mihomo（ADG和Mihomo的顺序可以交换
> > 
> > 但是我没测试过，理论可行
> 
> DNSmasq 端口改为0 Adguardhome 端口设置53 adg 上游指向 nikki ， 发现 adg不显示客户端ip 和请求的dns，是哪没设置对嘛？

dnsmasq不会向后传递客户端IP，你可以选择修改dnsmasq的dns端口为其他端口，设置adguardhome端口为53
注意这样设置之后需要修改lan口的dhcp，添加dhcp option，`6,0.0.0.0`，否则dhcp服务器不会下发DNS服务器到客户端（主路由模式，旁路有没用过）

**Comment by binzi723** [comment]
请教，r4s安装的istore OS系统，应该下载对应的哪个链接？

**Reply by t20240919** [reply]
mihomo_aarch64_generic.tar.gz
应该是这个,具体你查下你cpu信息.

**Reply by binzi723** [reply]
![CleanShot 2024-10-10 at 23 28 45](https://github.com/user-attachments/assets/4cae678b-8afe-4460-a764-9e8c13e642bf)
FriendlyElec NanoPi R4S
ARMv8 Processor rev 4
rockchip/armv8

**Reply by binzi723** [reply]
按照您说的下载了aarch64链接里的文件，但无法安装。

**Reply by t20240919** [reply]
先安装mihomo,再luci-app-mihomo,再luci-i18n-mihomo-zh-cn.
就是内核,图像控制界面,翻译,按顺序来.

**Reply by morytyann** [reply]
iStore好像不是firewall4吧，那没办法

**Reply by binzi723** [reply]
哦哦……😂
谢谢了 @morytyann @t20240919 
还要请教一下，哪里有可以装iStore的版本的？

**Reply by t20240919** [reply]
iStore只是个皮肤马甲,可以自行根据需求编译.https://github.com/istoreos/istoreos

**Reply by morytyann** [reply]
https://github.com/istoreos/istoreos/issues/1778#issue-2479819195

**Comment by t20240919** [comment]
你好v6语法是这样吗？不知道怎么填 ，[2402:4e00::]         "2402:4e00::"     "[2402:4e00::]"       
![屏幕截图 2024-11-11 200035](https://github.com/user-attachments/assets/83a9fd9e-d3b5-4c4a-bc99-c2e9452fa6f1)

**Reply by morytyann** [reply]
不需要转义，直接写引号里的内容应该就可以吧

**Reply by t20240919** [reply]
👌👍

**Comment by hanling2805** [comment]
保存表单时出错： 选项“要代理的 TCP 目标端口”不能为空。 这个怎么办？

**Reply by morytyann** [reply]
![image](https://github.com/user-attachments/assets/ae5dd59a-f7c6-4e6c-9d8b-0d766db97e97)

选一下全部端口

**Reply by hanling2805** [reply]
感谢

**Comment by halfroom** [comment]
按照README安装的，咋没有嗅探设置了

**Reply by t20240919** [reply]
直接添加到配置文件中
sniffer:
  enable: true
  force-dns-mapping: false
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80]
    TLS:
      ports: [443]
    QUIC:
      ports: [443]

如果你是fake IP  一般不需要配置嗅探，fakeip模式已经有域名映射了。 mate版的redir-host也是远程传递域名。除非你用Normal模式，一般不需要配置嗅探。

**Reply by t20240919** [reply]
而且配置嗅探，日志会出现很多类似level=warning msg的嗅探失败错误，未来如果出现问题，会给排查造成麻烦。
推荐Normal模式开启嗅探，fake IP和redir-host模式没有必要开嗅探。

**Reply by halfroom** [reply]
我就是redir-host，然后在局域网下面NAS机器配置mihomo作为它的网关，当做旁路由，经测试，开启嗅探才能正常访问，不然在日志看看到大量解析的ip地址，无法匹配规则出站，开启嗅探就正常了。
现在还有一个问题，我在NAS上开放的公网端口转发，全都不能正常访问了，这个是不是无解？

**Reply by morytyann** [reply]
DNS也需要指向旁路由

**Reply by halfroom** [reply]
这能解决嗅探的问题，还是连公网端口映射也可以解决

**Reply by morytyann** [reply]
解决嗅探问题。

端口转发的问题，你试试把环回源IP改为使用外部IP地址。
![image](https://github.com/user-attachments/assets/5204eb95-3153-4ba5-9580-a7425089a0bd)

**Reply by halfroom** [reply]
好的，多谢，晚上回去试试，再报结果

**Reply by halfroom** [reply]
我还没说一下我的网络拓扑。。我的TrueNAS有两张网卡，直通一张做软路由的，所以软路由只做了一个网口。
设置了DNS为旁路由，还是不行。这是我tun和dns的配置，其中dns-hijack无论配置53端口还是1053，都不行，但有一点很奇怪，看起来偶尔有那么一两条是正常走规则的，比如截图里的ntp3.aliyun.com，但我终端里curl https://google.com，和docker pull，日志里都不识别为域名。
![image](https://github.com/user-attachments/assets/d03122ed-3619-4e8a-b73b-44140148a19f)
![image](https://github.com/user-attachments/assets/637df325-769b-49cf-ab99-0603ce737a60)

配置文件：
```yaml
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-redirect: false
  route-address:
    - 0.0.0.0/1
    - 128.0.0.0/1
    - ::/1
    - 8000::/1
  auto-detect-interface: true
  dns-hijack:
    - any:53
  device: mihomo
  mtu: 9000
  strict-route: true
  endpoint-independent-nat: true
dns:
  enable: true
  ipv6: true
  use-hosts: false
  use-system-hosts: true
  default-nameserver:
    - 192.168.x.1
    - 223.5.5.5
    - 114.114.114.114
  nameserver:
    - 192.168.x.1
    - 223.5.5.5
    - 114.114.114.114
  nameserver-policy: {}
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
  fallback:
    - 1.1.1.1
    - 8.8.8.8
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - +.facebook.com
      - +.youtube.com
      - +.google.com
  prefer-h3: false



```

```log
time="2024-11-21T23:24:59.793960998+08:00" level=info msg="Initial configuration complete, total time: 905ms"
time="2024-11-21T23:24:59.794259878+08:00" level=info msg="RESTful API listening at: [::]:9090"
time="2024-11-21T23:24:59.800660982+08:00" level=info msg="Sniffer is closed"
time="2024-11-21T23:24:59.800679046+08:00" level=info msg="Use tcp concurrent"
time="2024-11-21T23:24:59.800744128+08:00" level=info msg="DNS server listening at: [::]:1053"
time="2024-11-21T23:24:59.80079862+08:00" level=info msg="HTTP proxy listening at: [::]:8080"
time="2024-11-21T23:24:59.800844997+08:00" level=info msg="SOCKS proxy listening at: [::]:1080"
time="2024-11-21T23:24:59.800896023+08:00" level=info msg="Redirect proxy listening at: [::]:7891"
time="2024-11-21T23:24:59.80095331+08:00" level=info msg="TProxy server listening at: [::]:7892"
time="2024-11-21T23:24:59.800979529+08:00" level=info msg="Mixed(http+socks) proxy listening at: [::]:7890"
time="2024-11-21T23:24:59.805681459+08:00" level=info msg="[TUN] Tun adapter listening at: mihomo([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 9000, auto route: true, auto redir: false, ip stack: Mixed"
```

**Reply by halfroom** [reply]
今天改了一下sniffer，就莫名奇妙的公网端口转发访问也好了，，而且我也没把NAS的DNS配置成旁路由的DNS。以下是我的sniffer配置，就是把force-dns-mapper从true改成了false，然后重启了一下NAS的网络服务。真是瞎猫碰见了死耗子，不知道哪里的操作触发成功了。
```yaml
sniffer:
  enable: true
  force-dns-mapping: false
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - +.v2ex.com
  skip-domain:
    - Mijia Cloud
```
