### DISCUSSION TITLE
《关于启用路由器代理后，第三方DNS插件访问53端口的UDP查询受阻这档子事》[doge]

### DISCUSSION THREAD

**Discussion by xiandu999-yu** [nikkinikki-org/OpenWrt-nikki#500] [General]
起因是smartdns更新的ui
![image](https://github.com/user-attachments/assets/46a3b31a-c07a-4716-bec6-749f24f3beaf)
跑了裸核mihomo的DNS模块
![image](https://github.com/user-attachments/assets/40797e8a-e3fd-4959-9a40-f4a34ee61930)
最后把DNS劫持关了就正常了....

**Comment by thisdk** [comment]
我感觉...就clash这么强大的dns模块.都能给rule-set指定dns这么细的功能了.用好这个功能.比第三方dns插件强大多了.

举个例子:
```yaml
dns:
  enable: true
  listen: :1053
  ipv6: false
  prefer-h3: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  respect-rules: true
  use-hosts: true
  use-system-hosts: true
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  nameserver:
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
  fallback:
    - https://8.8.8.8/dns-query
  proxy-server-nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
  nameserver-policy:
    rule-set:private-domain,cn-domain,microsoft-domain-cn,google-domain-cn,apple-domain-cn,cloudflare-domain-cn,steam-domain-cn,game-domain-cn,ntp-domain-cn,geolocation-cn:
      - https://120.53.53.53/dns-query
      - https://223.6.6.6/dns-query
    rule-set:microsoft-domain,github-domain,openai-domain,youtube-domain,cloudflare-domain,steam-domain,twitter-domain,telegram-domain,twitch-domain,netflix-domain,nexon-domain,geolocation-!cn:
      - https://8.8.8.8/dns-query#h3=true
      - https://1.1.1.1/dns-query#h3=true

```
