### DISCUSSION TITLE
启动很慢，占用异常，tun网卡检查不到

### DISCUSSION THREAD

**Discussion by Ailina0728** [nikkinikki-org/OpenWrt-nikki#578] [Q&A]
![error1](https://github.com/user-attachments/assets/6e7150b5-1a05-4ead-b2e6-026483094567)
![error2](https://github.com/user-attachments/assets/b8118472-ef63-4953-b794-770ca93001d7)
![error3](https://github.com/user-attachments/assets/21516135-9536-4b7e-b66b-11a6b25efc43)
设备mt7986，immortalwrt 24.10.1 内核6.6 nftable  。mihomo版本1.22.2
首先是等待tun上线，但是等待一小会儿就超时然后退出了，检查内核日志也没有相关的报错且正常执行，大概3分钟左右能打开webui面板，代理不生效，空载200+MB内存占用。手动重载几次服务偶尔会检测到tun网卡，此时才能使用，连接10多个占用100+mb内存，50个就200多了。读取配置文件很慢，tun网卡手动创建的nikki，防火墙也正常
不知道什么原因，之前试过裸核跑singbox几秒钟就可以上线

**Comment by morytyann** [comment]
算命：路由器朝向问题

**Reply by Ailina0728** [reply]
哈哈，再加上调试日志，配置文件，
[debug (1).log](https://github.com/user-attachments/files/20202476/debug.1.log)
![error4](https://github.com/user-attachments/assets/8eb1129c-f050-44dc-91d9-e85e8d695c3f)
![error5](https://github.com/user-attachments/assets/e251dede-fe40-45c6-a605-ab49e09d70b5)

```yaml
allow-lan: true          
port: 7890                
socks-port: 7891          
mixed-port: 7892         
redir-port: 7893          
tproxy-port: 7894        

log-level: warning                 
mode: rule                        
find-process-mode: 'off'           
# interface-name: en0             
bind-address: "*"                  
ipv6: true                         
unified-delay: true                
tcp-concurrent: true              
disable-keep-alive: false         
keep-alive-idle: 600              
keep-alive-interval: 15           
global-client-fingerprint: chrome  

external-controller: '[::]:9090'               
     
secret: ""                                    
        
external-ui-name: zashboard               
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"                  
experimental:                                
   quic-go-disable-gso: false            
            
       

profile:
  store-selected: true           
  store-fake-ip: true            

sniffer:
  enable: true                  
  force-dns-mapping: false      
  parse-pure-ip: false          
  override-destination: false   
  sniff:                         
    HTTP:                        
      ports: [80, 8080]
      override-destination: true 
    TLS:                        
      ports: [443, 8443]
    QUIC:                       
      ports: [443, 8443]
 

tun:
  enable: true                                                                                     
  stack: mixed                                           
  dns-hijack: ["any:53", "tcp://any:53"]                 
  mtu: 9000                                              
  gso: false                                              
  gso-max-size: 65536                                    
  udp-timeout: 300                                      
  auto-route: true                                       
  auto-redirect: true                                                                    
  auto-detect-interface: true                             
  iproute2-table-index: 2022                              
  iproute2-rule-index: 9000                               
  endpoint-independent-nat: false                        


dns:
  enable: true           
  listen: 0.0.0.0:1053   
  ipv6: true             
  ipv6-timeout: 300      
  respect-rules: false
  prefer-h3: false                                                                     
  enhanced-mode: fake-ip                                 
  fake-ip-range: 198.18.0.1/16                           
  fake-ip-filter-mode: blacklist                         
```
  
再帮忙看看呗

**Reply by morytyann** [reply]
删掉这几个再试试？

```yaml
tun:
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  iproute2-table-index: 2022
  iproute2-rule-index: 9000
```
