### DISCUSSION TITLE
一个玄学问题

### DISCUSSION THREAD

**Discussion by liumingan** [nikkinikki-org/OpenWrt-nikki#99] [Q&A]
openwrt -mihomo正常运行中重启或者停止，60%以上的机率会连接不上节点。
发现在ping不通节点了
解决办法是重启wan或者重启openwrt，有人遇到过同样的问题吗？

op纯净没有其它任何插件运行
节点是域名不是IP
service是IP的节点没有这个问题

**Comment by liumingan** [comment]
研究了好几天，依然没有找到问题在哪儿，在mihomo停止运行的环境下，什么都不做，也许过3-5分可以恢复，也许重启一下防火墙或者dnsmasq可以恢复

**Comment by morytyann** [comment]
配置一下出站接口试试？

**Comment by liumingan** [comment]
我配置了出站接口为wan，可以改成lan？

Joseph Mory ***@***.***> 于2024年8月21日周三 21:36写道：

> 配置一下出站接口试试？
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/morytyann/OpenWrt-mihomo/discussions/99#discussioncomment-10407860>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHST534KGJBCPWQZKFCFC5LZSSJWRAVCNFSM6AAAAABM3W6ZFOVHI2DSMVQWIX3LMV43URDJONRXK43TNFXW4Q3PNVWWK3TUHMYTANBQG44DMMA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>



***********************************************

**Comment by liumingan** [comment]
配置为lan不行，连不上网了

Liu Mingan ***@***.***> 于2024年8月21日周三 22:17写道：

**Comment by liumingan** [comment]
[image: image.png]

Liu Mingan ***@***.***> 于2024年8月21日周三 22:46写道：

**Comment by liumingan** [comment]
sbs 要把出站流量打上mark？

Liu Mingan ***@***.***> 于2024年8月21日周三 22:57写道：

**Comment by morytyann** [comment]
SBS是什么？😢

**Reply by liumingan** [reply]
打错了，应该是：是不是

**Comment by morytyann** [comment]
我感觉是DNS无法解析节点域名导致的问题，可以朝这个方向查查，你可以等到出问题的时候，在路由器运行`nslookup 你的节点域名`看看能否获取到结果。

**Comment by liumingan** [comment]
等到出问题的时候，在路由器运行nslookup 可以获取到结果，ping的也是节点的ip地址

Joseph Mory ***@***.***> 于2024年8月22日周四 13:29写道：

> 我感觉是DNS无法解析节点域名导致的问题，可以朝这个方向查查，你可以等到出问题的时候，在路由器运行nslookup 你的节点域名看看能否获取到结果。
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/morytyann/OpenWrt-mihomo/discussions/99#discussioncomment-10415087>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHST536AIYQKYHHNJ5NUPW3ZSVZNDAVCNFSM6AAAAABM3W6ZFOVHI2DSMVQWIX3LMV43URDJONRXK43TNFXW4Q3PNVWWK3TUHMYTANBRGUYDQNY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>
等到出问题的时候，在路由器运行nslookup 可以获取到结果，ping的也是节点的ip地址，节点的ip地址time out

**Reply by liumingan** [reply]
出问题的时候，如果插件已经运行，是无法解析节点域名的，这个时候关闭插件，在路由器里运行网络诊断，可以解析出节点域名，但ping不通

**Reply by liumingan** [reply]
这个时候就出现玄学了，也许一会儿就通了，也许一直不通.......

**Reply by morytyann** [reply]
感觉像是nftables规则炸了，等出问题的时候`nft list ruleset`看看，再就是最好把核心日志级别调整为debug，也贴上来

**Comment by morytyann** [comment]
解析出来的不是Fake-IP吧？难道是节点炸了😂，要不你切换到OpenClash，长时间用一用，看会不会有问题。

**Reply by liumingan** [reply]
```
dns:
  cache-algorithm: arc
  enable: true
  enhanced-mode: redir-host # redir-host or fake-ip
  prefer-h3: false # 是否开启 DoH 支持 HTTP/3，将并发尝试
  listen: 0.0.0.0:1053 # 开启 DNS 服务器监听
  use-hosts: true
  ipv6: true
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '+.*'
  default-nameserver:
    - 114.114.114.114
    - 119.29.29.29
  # 配置后面的nameserver、fallback和nameserver-policy向dns服务器的连接过程是否遵守遵守rules规则
  # 如果为false（默认值）则这三部分的dns服务器在未特别指定的情况下会直连
  # 如果为true，将会按照rules的规则匹配链接方式（走代理或直连），如果有特别指定则任然以指定值为准
  # 仅当proxy-server-nameserver非空时可以开启此选项, 强烈不建议和prefer-h3一起使用
  # 此外，这三者配置中的dns服务器如果出现域名会采用default-nameserver配置项解析，也请确保正确配置default-nameserver
  respect-rules: true # false  true
  nameserver:
    - 'tls://8.8.4.4'
    - 'tls://one.one.one.one'
    - 'quic://dns.adguard.com:784'
  nameserver-policy:
    'geosite:baidu': '114.114.114.114'
    'geosite:alibaba': '223.5.5.5'
    'geosite:tencent': '119.29.29.29'
    "geosite:category-ads-all": rcode://success
    'geosite:cn,private,category-games@cn':
      - '218.106.127.114'
      - '218.104.111.114'
    #  - 'https://223.6.6.6/dns-query'
    'geosite:geolocation-!cn,google,gfw,youtube,pixiv,bing,twitter,openai':
      - 'tls://8.8.4.4'
      - 'https://dns.google/dns-query'
      - 'tls://208.67.222.222'
      - 'https://cloudflare-dns.com/dns-query'
      - 'https://mozilla.cloudflare-dns.com/dns-query'
  proxy-server-nameserver: # 专用于节点域名解析的 DNS 服务器
    - '1.1.1.1'
    - '114.114.115.115'
#    - 'https://doh.pub/dns-query'
```
